### ISSUE TITLE
Really awsome . But i need some direction from you

### ISSUE THREAD

**Issue by tahercoolguy** [sleekmike/Finetune_GPT-J_6B_8-bit#2]
Really awsome Work . I was wonder how you convert slim weight which floating point 16 provided by el euther to floating point 8 . Can you please direct if you want to do it for other models

Thanks

**Comment by sleekmike** [comment]
Hello, sorry just seeing this now, You can check the tutorial and follow the link I believe you will find the solution to your issue.
