### ISSUE TITLE
Working Fine

### ISSUE THREAD

**Issue by 22Mukesh22** [sleekmike/Finetune_GPT-J_6B_8-bit#3]

**Comment by 22Mukesh22** [comment]
@sleekmike Please help me on the above issue , I didn't find anything from Google which can help me up. I am not able to get loss backward while trianing

**Comment by 22Mukesh22** [comment]
Done

**Comment by gururise** [comment]
How did you fix this error? I'm getting the same error:
```
RuntimeError: Output 0 of DequantizeAndLinearBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.
```

**Comment by lnguyenfx** [comment]
> How did you fix this error? I'm getting the same error:
> RuntimeError: Output 0 of DequantizeAndLinearBackward is a view and is being modified inplace

In _gpt-j-6b-8-bit.py_, modify line 45.

From:
`output = DequantizeAndLinear.apply(input, self.weight, self.absmax, self.code, self.bias)`

To:
`output = DequantizeAndLinear.apply(input, self.weight, self.absmax, self.code, self.bias).clone()`
