### ISSUE TITLE
Finetuning error

### ISSUE THREAD

**Issue by ali-chaudhry8** [sleekmike/Finetune_GPT-J_6B_8-bit#4]
Hi, 

I get this error when fine tuning the model: 

RuntimeError: Output 0 of DequantizeAndLinearBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can fix this by cloning the output of the custom Function.

Do I need to save a checkpoint to avoid this? Not sure how it would work?

Thanks,
a

**Comment by ali-chaudhry8** [comment]
Resolved it!

**Comment by jaydeep-dxfactor** [comment]
hi, @ali-chaudhry8 can you tell me how you solved it..!!

**Comment by ayubih** [comment]
Hi @ali-chaudhry8  could you share how you resolved this error. I'm facing the same thing.

**Comment by thandal** [comment]
See https://github.com/sleekmike/Finetune_GPT-J_6B_8-bit/issues/3
