### ISSUE TITLE
Running without CUDA (bitsandbytes)

### ISSUE THREAD

**Issue by NotNite** [sleekmike/Finetune_GPT-J_6B_8-bit#5]
Heya,

Almost got this working with DirectML on Windows, but bitsandbytes requires CUDA on Linux. I'm gonna run out of VRAM if I don't do the monkey patching seen in the repo, so I was wondering if you had any ideas to not depend on it.

Thanks!

**Comment by sleekmike** [comment]
Hi @NotNite, 

I have not tried this on windows, I have only tried on Linux, Colab and Mac OS. 
I don't think you need to do the patching...You can just directly download the 8-bit weights, adjust some of the models params in the code and try loading it and running inference or fine-tuning(requires more memory and is also more computationally intensive.)

Mind you, the weights are over 10 gig in size so you probably need a PC or server with 16 gig RAM or above to have everything working smoothly.

You can reach me via my socials if you need further assistance. Thanks!
